### ISSUE TITLE
(Crash) Incompatibility with KubeJs

### ISSUE THREAD

**Issue by cntrik** [KrLite/Equator-v2#1]
Fabric 1.20.1 
Equator 2.5.3

Steps to reproduce:
1. Launch Minecraft
2. Go to Singleplayer Screen
[Game Crashes ](https://gist.github.com/Afrocntrik/e292241690341962659e4ea525b483e8)

**Comment by KrLite** [comment]
Thanks for reporting!
The bug sounds weird. I will check it soon.

**Comment by cntrik** [comment]
With or without Equator game crashes my apologies, I will mark this as closed.

**Comment by KrLite** [comment]
> With or without Equator game crashes my apologies, I will mark this as closed.

Sorry for hearing that, it might be a KubeJs issue then. Anyway thanks for reporting.
