### ISSUE TITLE
(Bug) Game Freezes utilizing Mod Menu or Configured 

### ISSUE THREAD

**Issue by cntrik** [KrLite/Equator-v2#2]
Fabric 1.20.1 
Equator 2.5.3

Steps to reproduce:
1. Launch Minecraft
2. Go to Mod Menu or Configured
3. Scroll Up/Down to Equator
Game will freeze for a few seconds

**Comment by KrLite** [comment]
Thanks for reporting!
As a library, when loading only **Equator v2** and other unrelated mods in Minecraft, nothing should actually happen. However, I will check the situation you mentioned soon.

**Comment by KrLite** [comment]
This is mysterious as some slight changes have made a huge difference. I estimate that this should never happen after the next version.
Also, **Equator** is going to have the `Library` ModMenu badge so that you won't see it very often then.

**Comment by KrLite** [comment]
Fixed in [`v2.5.4`](https://modrinth.com/mod/equator/version/1.20-v2.5.4).
